const path = require('path');
const postCSSPlugins = [
	require('autoprefixer'),
	require('postcss-nested'),
	require('postcss-simple-vars')
];

module.exports = {
	entry: './app/assets/scripts/App.js',	/* Main .js file to load that contains all dependencies */
	output: {
		filename: 'bundeld.js',	/* Name of the autogenerated file with all dependencies bundled together */
		path: path.resolve(__dirname,'app')	/* Directory where to put the autogenerated file  */
	},
	module: {
		rules: [
			{
				test: /\.css$/i, /* Only if file ends in .css */
				use: ['style-loader','css-loader', {loader: 'postcss-loader', options: {plugins: postCSSPlugins}}]
			}
		]
	},
	devServer: { /* DevServer will watch for changes in contentBase directory and inject those to the running browser(s) */
		contentBase: path.join(__dirname, 'app'),	/* Base folder where our index.html file lives */
		hot: true, /* Auto inject at save. The main entry point .js file must contain following: if (module.hot) module.hot.accept(); */
		port: 3000
	},
	mode: 'development' 
}
 

